spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent?currentSchema=rent
    username: postgres
    password: alejo

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true